import turtle
turtle.setup(800,600)
window=turtle.Screen()
window.title("Wellcome turtle programming")
t=turtle.Turtle()
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.hideturtle()
window.exitonclick()
