fp=open("intro.txt","w")
fname=input("Enter your first name:")
sname=input("Enter your second name:")
lname=input("Enter your last name:")
add=input("Enter your address:")
fp.write(fname)
fp.write("\n")
fp.write(sname)
fp.write("\n")
fp.write(lname)
fp.write("\n")
fp.write(add)
fp.write("\n")
fp.close()
